export const emailPattern = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;

export const intakeInitialValues = {
  first_name: '',
  last_name: '',
  preferred_name: '',
  date_of_birth: '',
  phone: '',
  email: '',
  for_minor_child: '',
  guardian_signature: '',
  relationship_with_child: '',
  sex_assigned_at_birth: '',
  gender: '',
  address_one: '',
  address_two: '',
  city: '',
  state: '',
  zip_code: '',
  reason_for_visit: '',
  mental_health_care_type: '',
  therapy_availability: '',
  hearing_impairment: '',
  interpreter_guidelines: '',
  emergency_contact_info: '',
  emergency_contact_phone: '',
  insurance_id: '',
  insurance_card_front: '',
  insurance_card_back: '',
  credit_card_number: '',
  credit_card_exp_date: '',
  credit_card_csv: '',
  billing_zip_code: '',

  // New fields
  seen_health_professional: '',
  symptoms_past_six_months: [],
  symptoms_other: '',
  current_medications: '',
  medication_allergies: '',
  alcohol_frequency: '',
  alcohol_quantity: '',
  recreational_drug_use: '',
  hospitalized_psych: '',
  hospitalized_psych_details: '',
  family_history_mental_illness: '',
  personal_medical_history: [],
  personal_medical_history_other: '',
  height: '',
  weight: '',
  pregnant_or_breastfeeding: '',
  recent_physical_exam: '',
  recent_physical_exam_details: '',
  education_level: '',
  current_occupation: '',
  living_situation: '',
  has_weapons: '',
  honesty: '',
  honesty_signature: '',

  policy_agreement: '',
  policy_agreement_signature: '',

  relationship_status: '',
  relationship_status_other: '',
  appointment_address: '',
  appointment_city: '',
  appointment_state: '',
  photo_ID: '',

  insurance_provider: '',
};

export const creditCardInitialValues = {
  patient_name: '',
  date_of_birth: '',
  cardholder_name: '',

  address_one: '',
  address_two: '',
  city: '',
  state: '',
  zip_code: '',

  credit_card_number: '',
  credit_card_exp_date: '',
  credit_card_csv: '',

  signature: '',
  signature_date: new Date(),
};

export const providerOnboardingInitialValues = {
  first_name: '',
  last_name: '',
  date_of_birth: '',
  phone: '',
  email: '',
  hear_about: '',
  state_of_license: '',
  state_of_license_st: '',
  pecos_consent: '',
  policy_agreement: '',
  policy_agreement_signature: '',
  therapy_sessions: [],
  therapy_session_others: '',
  languages: [],
};
